addons:
  sonarcloud:
    organization: renskrauweel
    token:
      secure: SLhm2D2D90XQPQ2HOZWuGPtluPaJIXB1QFrI8dxR3K7XzqiVBijqrlxEkn8PPSazfOji/B/7YsHjnHHr/LQjQLzlZis5fk2zT2WVMsLr6AjegsdmcpO1CEkeeaUmThWhPUedXgSiK76niaXJc3lcxeEwkHswNRIJJospItEwsVfxXn+lu8fA+3ct715pJT6zlBDKdKyNEwzVPFMYXWOh2y0GClVgV1BZkXiWxZrXPffavTw7e5JsABZysOolkVzqxKlZCTgDP5Le+FU5ETuXWe4Ar5p0BhgQtHHGe5ae+8KMd/DgvXKwqrkMkXmlgP8qVHnDYa4pZGGzqvofPhO3Jigo7jsHNFEM5jCK45PWJIr6abg2GJPBBy7neTp9gwFYH+SOria/ODbWgKhGXL4lZW4OW3GnT1nlNqzqAsg2WsOuGFHAqCR1O6Pdl7aLKa8iZcbbukBpwvTs2CzNLzBPShm/lv5F1gsMyIEm2trXppLfxBen1cEkL7LnwPhDcOkir/Swvap6QBMuL21qI6LGHmCo2yC4VqFaQGWTaYJcib15LHVkNvJ7Xg408rpdhETPHKXKNEWvkCECUDrnS//CaSquCz/fwrX7hlhIJj3D1tQrnMg9bHrOlmbAaYVXjoEGcOIz9DIgNRYWEBMIcPEtLKXXpgNvzKL1DVkB4xN/Dzc=
solution: RumbleRacer.sln
language: csharp
mono: none
dist: xenial
dotnet: 3.1
script:
- build-wrapper-linux-x86-64 --out-dir bw-output dotnet clean RumbleRacer.sln
- sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output -X
env:
  global:
  - secure: SLhm2D2D90XQPQ2HOZWuGPtluPaJIXB1QFrI8dxR3K7XzqiVBijqrlxEkn8PPSazfOji/B/7YsHjnHHr/LQjQLzlZis5fk2zT2WVMsLr6AjegsdmcpO1CEkeeaUmThWhPUedXgSiK76niaXJc3lcxeEwkHswNRIJJospItEwsVfxXn+lu8fA+3ct715pJT6zlBDKdKyNEwzVPFMYXWOh2y0GClVgV1BZkXiWxZrXPffavTw7e5JsABZysOolkVzqxKlZCTgDP5Le+FU5ETuXWe4Ar5p0BhgQtHHGe5ae+8KMd/DgvXKwqrkMkXmlgP8qVHnDYa4pZGGzqvofPhO3Jigo7jsHNFEM5jCK45PWJIr6abg2GJPBBy7neTp9gwFYH+SOria/ODbWgKhGXL4lZW4OW3GnT1nlNqzqAsg2WsOuGFHAqCR1O6Pdl7aLKa8iZcbbukBpwvTs2CzNLzBPShm/lv5F1gsMyIEm2trXppLfxBen1cEkL7LnwPhDcOkir/Swvap6QBMuL21qI6LGHmCo2yC4VqFaQGWTaYJcib15LHVkNvJ7Xg408rpdhETPHKXKNEWvkCECUDrnS//CaSquCz/fwrX7hlhIJj3D1tQrnMg9bHrOlmbAaYVXjoEGcOIz9DIgNRYWEBMIcPEtLKXXpgNvzKL1DVkB4xN/Dzc=
