addons:
  sonarcloud:
    organization: "renskrauweel"
    token:
      secure: "UfpUzKWeyd+imyI0kCP4SmbVEtxPOb1H+aAfqVsaVKwhcOzGygT5gn0x2jfxe6L2T9RhkkIIrE1pvxro1A7MynwiLqV45cCpkJJDWswEzYu8VHI6qOqhgSPMYWMq1Wqw027pxa6SdY1PUcyRx1VZ7gMoJoF9plT8N3ZS/8Zo2aLFq3JoRxinEZg3NglIAp/CCm8dsbtbEWZi5gh7scP8IrrOx8629QIInq2k7h6IkTeM5cWsgeAie/ubvZr3oBwgG0vCueGxdIYgitdHod6j0ITStlQ/BQr1TBjNAbn1yhJlC7YCAslF4FGPBmbe53fEKanv59tLYb6ytbkrhh8VxaPX8Vvhq6+JvcQr0pjLuQicubqCVfRTC2YDKDGKX0Kjy2nuMECRy8u+83jygTfMNKvQ6zbNQcMUbRw2FtAehNCtnotVyz9XgVIxI4/BiKYoZ9n7INutRw11GwLqbg8Xouq9l6aBm2DIIMMe189gNpqlb6xXoLX9DE2lI4SjhuZSPiAFTdT+VIThUA/HZx324zPANzKuyZf3hqINx3M33gngKarVegdFmVN2wsYggV4KgR7b0TCzNn21GRk7hA/3gH88CF1F08HBG8n3RocCzlKP+zrzjiRj1ocvabr3F2ZW/w1nx5WdbVD0tRHP1hBsA8JIuTBKCx43vGPdWxQxCME="
solution: RumbleRacer.sln
language: csharp
mono: none
dist: xenial
dotnet: 3.1

install:
  - dotnet tool install --global dotnet-sonarscanner

before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"

script:
#- dotnet tool install --global dotnet-sonarscanner
#- build-wrapper-linux-x86-64 --out-dir bw-output dotnet clean RumbleRacer.sln
#- sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
  - dotnet sonarscanner begin /k:"renskrauweel_RumbleRacer" /o:"renskrauweel"
  - dotnet build RumbleRacer.sln
  - dotnet sonarscanner end
