addons:
  sonarcloud:
    organization: renskrauweel
solution: RumbleRacer.sln
language: csharp
mono: none
dist: xenial
dotnet: 3.1
script:
  #- dotnet restore RumbleRacer.sln
#  - dotnet clean RumbleRacer.sln
  #- dotnet build RumbleRacer.sln --no-incremental
  - build-wrapper-linux-x86-64 --out-dir bw-output dotnet clean RumbleRacer.sln

#script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  #- build-wrapper-linux-x86-64 --out-dir bw-output dotnet build RumbleRacer.sln
  #- build-wrapper-linux-x86-64 --out-dir bw-output dotnet build
  #- dotnet restore
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
